### ISSUE TITLE
Suggestion - Negative Controls

### ISSUE THREAD

**Issue by sacred-rosary** [OhGeezCmon/VRC-AccessControl#2]
Currently you can select the GameObjects that _should_ show for the admins. I’m suggesting adding another string for GameObjects that _shouldn’t_ show for the admins. This would be greatly appreciated.

**Comment by OhGeezCmon** [comment]
Great suggestions, I updated the Prefab with this functionality.  I've done some testing, but please let me know if you encounter any bugs.

https://github.com/OhGeezCmon/VRC-AccessControl/releases/tag/v1.2

**Comment by OhGeezCmon** [comment]
@KenazEnigma Would love to hear how you found this Prefab... I haven't listed it anywhere, but it is in use in the Party Tub world.  Thanks for using it, and for giving feedback!
